package com.PRS.model.engine;

/** Why the engine refused an action. Rejection is always a return value, never an exception. */
public enum RejectionReason {
  GAME_OVER,
  NOT_YOUR_TURN,
  WRONG_PHASE,
  ROLE_UNAVAILABLE,
  NO_ISLAND_SPACE,
  TILE_UNAVAILABLE,
  QUARRY_NOT_ALLOWED,
  NO_CITY_SPACE,
  DUPLICATE_BUILDING,
  BUILDING_UNAVAILABLE,
  INSUFFICIENT_DOUBLOONS,
  GOOD_NOT_HELD,
  GOOD_NOT_PRODUCED,
  TRADING_HOUSE_FULL,
  DUPLICATE_GOOD_IN_TRADING_HOUSE,
  SHIP_UNAVAILABLE,
  SUBOPTIMAL_SHIP,
  WHARF_UNAVAILABLE,
  LOADING_IS_MANDATORY,
  INVALID_COLONIST_MOVE,
  COLONISTS_UNPLACED,
  INVALID_STORAGE
}
